# Generated by Django 4.0.3 on 2022-06-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='phone_number',
            field=models.CharField(default='06325688', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='municipal',
            field=models.CharField(default='ain djasser', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='batna', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street_adress',
            field=models.TextField(default='1st november', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default='05032', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
