# Generated by Django 4.0.3 on 2022-06-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_agency_phone_number_user_municipal_user_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'client'), (2, 'agency')], default=1),
            preserve_default=False,
        ),
    ]
