# Generated by Django 4.0.3 on 2022-06-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_client_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='zip_code',
        ),
    ]
