# Generated by Django 4.0.3 on 2022-06-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='property_type',
            field=models.TextField(choices=[('Apartement', 'Apartement'), ('Offices and businesses', 'Offices and businesses'), ('Land', 'Land')], null=True),
        ),
    ]
