# Generated by Django 4.0.3 on 2022-05-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_agency_user_alter_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerimages',
            name='image',
            field=models.ImageField(null=True, upload_to='offer_images'),
        ),
    ]
