# Generated by Django 4.0.3 on 2022-06-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_offer_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='longtitude',
        ),
    ]
