# Generated by Django 4.0.3 on 2022-05-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_offerimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimages',
            name='image',
            field=models.ImageField(default='defaults/default-offer-image.jpg', null=True, upload_to='offer_images'),
        ),
    ]
