# Generated by Django 4.0.3 on 2022-05-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_offerimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimages',
            name='image',
            field=models.ImageField(null=True, upload_to='offer_images'),
        ),
    ]
