# Generated by Django 4.0.3 on 2022-06-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_offer_latitude_remove_offer_longtitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='property_area',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='transaction_type',
            field=models.TextField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], null=True),
        ),
    ]
