# Generated by Django 4.0.3 on 2022-06-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_offer_property_area_offer_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='property_area',
            field=models.IntegerField(null=True),
        ),
    ]
