# Generated by Django 4.0.3 on 2022-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_comment_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(default=0),
        ),
    ]
