# Generated by Django 4.0.3 on 2022-05-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_comment_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='refrence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.comment'),
            preserve_default=False,
        ),
    ]
