# Generated by Django 4.0.3 on 2022-06-04 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='municipal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street_adress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='agency',
            name='municipal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='street_adress',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offer')),
            ],
        ),
    ]
