# Generated by Django 4.0.3 on 2022-06-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_user_municipal_remove_user_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='followed',
        ),
    ]
